version: "3.7"
services:
  expose:
    ports:
      - 127.0.0.1:8080:${PORT}
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
    build:
      args:
        username: ${USERNAME}
        password: ${PASSWORD}
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./expose.db:/root/.expose/expose.db
